### ISSUE TITLE
64-bit TF2 update (2024/04/18) fails to load plugin (workaround found)

### ISSUE THREAD

**Issue by Piogre** [ficool2/custom_items_games#3]
Today's TF2 update to the 64-bit launcher seems to have broken this

Launching the new default launcher tf_win64.exe yields the following:

> Loading unsigned module addons\custom_items_games.dll
> Access to secure servers is disabled.
> Unable to load plugin "addons/custom_items_games.dll"

The Team Fortress 2 folder has another launcher exe, "tf.exe" -- attempting to launch this yields a different (but still broken) result:

> Loading unsigned module addons\custom_items_games.dll
> Access to secure servers is disabled.
> [Custom Items Game] Found module info for client.dll: Start: 0x58EA0000 End: 0x59D32000 (E92000)
> [Custom Items Game] Found module info for server.dll: Start: 0x57AE0000 End: 0x5878D000 (CAD000)
> [Custom Items Game] Signature CTFItemSystem found at 0x57E9EC20 in server.dll
> [Custom Items Game] Failed to find signature for CCrypto::RSAVerifySignatureSHA256
> [Custom Items Game] Failed to find signature for CEconItemSystem::ParseItemSchemaFile
> [Custom Items Game] Failed to find signature for CGCUpdateItemSchema::BYieldingRunGCJob
> Failed to load plugin "addons/custom_items_games.dll"

**Comment by Piogre** [comment]
I've found a workaround for the time being:

by reverting to the pre_07_25_23_demos beta branch (which this plugin handily makes useable) and launching with a .bat file:

> hl2.exe -game tf -novid -insecure

This plugin loads and successfully loads altered warpaint code in proto_defs (haven't tested items_game_custom changes but I'd assume it works too)

EDIT: have since tested with items_game_custom and it indeed works too

**Comment by ficool2** [comment]
Just added support for the 64bit version
