### ISSUE TITLE
Plugin issue with 64bit 

### ISSUE THREAD

**Issue by 7-0r** [ficool2/custom_items_games#4]
![image](https://github.com/ficool2/custom_items_games/assets/134168898/c40b8842-8995-4fe2-bb06-60e0513047ab)
i've used the method of renaming hl2.exe to tf_win64.exe and when i launch i get this error.

**Comment by Edoors2** [comment]
Go into the custom item schema and comment out/remove the entire entry for the crypt creeper. This has been an issue before the 64-bit update,.

**Comment by ficool2** [comment]
Just added support for the 64bit version
